In [1]:
import pandas as pd 
import numpy as np

In [2]:
vendas_db_caminho = 'db\\Base_analitica_vendas.xlsx'

In [3]:
vendas_db = pd.read_excel(vendas_db_caminho, sheet_name='Base')

### Clientes que mais faturaram

In [25]:
gastos_clientes = vendas_db.groupby(["DESCRICAOCLIENTE"])["VALORLIQUIDO"].sum().reset_index()
gastos_clientes = gastos_clientes.sort_values("VALORLIQUIDO", ascending=False)

gastos_clientes.head(10)

                   DESCRICAOCLIENTE  VALORLIQUIDO
28      LOGÍSTICA ESSENCIAL BEBIDAS    9166375.86
21     DISTRIBUIDORA VIDA DE BEBIDA    6826258.29
25      LOGÍSTICA BEBIDAS DO BRASIL    6655005.04
18  DISTRIBUIDORA REINO DAS BEBIDAS    6020606.70
15    DISTRIBUIDORA BRINDE & AMIGOS    5877731.95
24  LOGÍSTICA BEBIDAS ATACADO FELIZ    5845048.98
3     ATACADISTA SELEÇÃO DE BEBIDAS    5406854.63
19  DISTRIBUIDORA SABOR DAS BEBIDAS    5199755.90
35   REDE BRINDE FELIZ DISTRIBUIÇÃO    5008056.65
11          COMERCIAL ALPHA BEBIDAS    4809729.52

###  Produtos que mais faturaram por cliente

In [42]:
gastos_clientes = vendas_db.groupby(["DESCRICAOCLIENTE", "NOMEPRODUTO"])[["VALORLIQUIDO", "VOLUME"]].sum().reset_index()
gastos_clientes = gastos_clientes.sort_values("VALORLIQUIDO", ascending=False)

gastos_clientes.head(15)

,DESCRICAOCLIENTE,NOMEPRODUTO,VALORLIQUIDO,VOLUME
2145,LOGÍSTICA ESSENCIAL BEBIDAS,Cerveja Puro Malte Premium 355ml,1684583.72,15700
1597,DISTRIBUIDORA VIDA DE BEBIDA,Cerveja Puro Malte Premium 355ml,1015421.50,11900
1117,DISTRIBUIDORA BRINDE & AMIGOS,Drink Misto Senses 269ml,941615.29,4389
1113,DISTRIBUIDORA BRINDE & AMIGOS,Drink Misto Maracujá 269ml,907738.93,4983
1915,LOGÍSTICA BEBIDAS DO BRASIL,Drink Misto Senses 269ml,889578.07,4131
2328,LOGÍSTICA GUARDA BEBIDAS,Drink Misto Melancia 269ml,809683.66,3606
1614,DISTRIBUIDORA VIDA DE BEBIDA,Drink Misto Senses 269ml,805670.46,1443
1610,DISTRIBUIDORA VIDA DE BEBIDA,Drink Misto Maracujá 269ml,800307.48,2466
1911,LOGÍSTICA BEBIDAS DO BRASIL,Drink Misto Maracujá 269ml,796247.50,4580
1912,LOGÍSTICA BEBIDAS DO BRASIL,Drink Misto Melancia 269ml,778947.65,5319
2140,LOGÍSTICA ESSENCIAL BEBIDAS,Cerveja Artesanal Alpha Gold 600ml,740001.56,6425
2405,LOGÍSTICA INTEGRAL DE BEBIDAS,Cooler de Vinho Rosé 750ml,705120.98,259
225,ATACADISTA SELEÇÃO DE BEBIDAS,Drink Misto Melancia 269ml,704794.91,2969
1830,LOGÍSTICA BEBIDAS ATACADO FELIZ,Drink Misto Senses 269ml,682771.69,3405
1813,LOGÍSTICA BEBIDAS ATACADO FELIZ,Cerveja Puro Malte Premium 355ml,676098.00,18100

In [29]:
vendas_db.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

### Agregação de múltiplas métricas por diferentes colunas

In [43]:
clientes = (
    vendas_db.groupby("DESCRICAOCLIENTE")
    .agg({
        "VALORLIQUIDO": "sum",
        "VOLUME": "sum",
    })
    .reset_index()
)

clientes.head(5)

                DESCRICAOCLIENTE  VALORLIQUIDO  VOLUME
0        ATACADISTA BRINDE AMIGO    4295470.68   48432
1         ATACADISTA BRINDE FINO     566415.28    6917
2      ATACADISTA BRINDE SUPREMO     301509.72    2321
3  ATACADISTA SELEÇÃO DE BEBIDAS    5406854.63   44891
4           ATACADO BRINDE & CIA    2387934.45   31817

### Agregação de múltiplas métricas por coluna

In [40]:
vendas_db.groupby(["DESCRICAOGRUPOPRODUTO"])["VALORLIQUIDO"].agg(["sum", "mean", "min", "max"]).reset_index().sample(7)

,DESCRICAOGRUPOPRODUTO,sum,mean,min,max
24,Cervejas de Grande Produção,2261.56,150.770667,29.04,389.09
12,Categoria de Bebidas Diversas,7592.89,71.631038,0.01,538.16
25,Controle de Qualidade de Bebidas,680409.65,3677.890000,0.00,44058.19
23,Cervejas Regionais,1377180.01,2228.446618,-1347.25,75756.50
41,Refrigerantes Premium,162.20,81.100000,64.88,97.32
0,Base para Bebidas Alcoólicas,1963.05,218.116667,33.47,960.00
35,Insumos para Produção de Bebidas,2077461.06,2881.360693,-842.50,17895.18