In [127]:
import pandas as pd 
import numpy as np

In [2]:
vendas_db_caminho = 'db\\Base_analitica_vendas.xlsx'

In [3]:
vendas_db = pd.read_excel(vendas_db_caminho, sheet_name='Base')

In [ ]:
vendas_db["VALORUNITARIO"] = vendas_db["VALORLIQUIDO"] / vendas_db["VOLUME"] 
vendas_db.head(4)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,VALORUNITARIO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41,157.4700
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87,39.4774
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46,88.8920
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90,397.9000

In [6]:
vendas_db = vendas_db.assign(
    VOLUME_DOBRADO = vendas_db["VOLUME"] * 2,
    VALORLIQUIDO_DOBRADO = vendas_db["VALORLIQUIDO"] * 2,
)

In [7]:
vendas_db.tail(3)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,VALORUNITARIO,VOLUME_DOBRADO,VALORLIQUIDO_DOBRADO
40618,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94,172.66,18,3107.88
40619,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10,184.51,20,3690.20
40620,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88,88.88,2,177.76

In [ ]:
vendas_db = vendas_db.rename(columns={
    "DATAEMISSAO": "DATAVENDA"
})

In [9]:
vendas_db.tail(3)

,DATAVENDA,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,VALORUNITARIO,VOLUME_DOBRADO,VALORLIQUIDO_DOBRADO
40618,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94,172.66,18,3107.88
40619,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10,184.51,20,3690.20
40620,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88,88.88,2,177.76

In [10]:
vendas_db[["TIPOFATURAMENTO", "DESCRICAOTIPOFATURAMENTO"]].drop_duplicates()

     TIPOFATURAMENTO DESCRICAOTIPOFATURAMENTO
0                  1                    VENDA
29                 3              BONIFICAÇÃO
372                2       DEVOLUÇÃO DE VENDA
470               14      DEVOLUÇÃO DE COMPRA
558               13                   COMPRA

In [11]:
mapeamento_operacao = {
    1: "Operação Comercial",
    2: "Operação de Devolução",
    3: "Amostra / Cortesia",
    13: "Operação Comercial",
    14: "Ajuste de Inventário" 
}

vendas_db["OPERAÇÃO"] = vendas_db["TIPOFATURAMENTO"].map(mapeamento_operacao)

In [122]:
vendas_db[["DESCRICAOTIPOFATURAMENTO", "OPERAÇÃO"]].sample(9)

      DESCRICAOTIPOFATURAMENTO               OPERAÇÃO
28335              BONIFICAÇÃO     Amostra / Cortesia
4104                     VENDA     Operação Comercial
28641                    VENDA     Operação Comercial
34741                    VENDA     Operação Comercial
29913                    VENDA     Operação Comercial
25974                    VENDA     Operação Comercial
11506                    VENDA     Operação Comercial
25221                    VENDA     Operação Comercial
22246       DEVOLUÇÃO DE VENDA  Operação de Devolução

In [123]:
def classificacao_valor(valor):
    if valor >= 5000: return "Alto"
    elif valor >= 3500: return "Mediano"
    else: return "Baixo"

vendas_db["CLASSIFICACAO_VALOR"] = vendas_db["VALORLIQUIDO"].apply(classificacao_valor)

In [125]:
vendas_db[["VALORLIQUIDO", "CLASSIFICACAO_VALOR"]].sample(5)

       VALORLIQUIDO CLASSIFICACAO_VALOR
22440       9669.00                Alto
8360         279.00               Baixo
21722        197.94               Baixo
33419        530.47               Baixo
27459       1991.28               Baixo

### Numpy.Where x Pandas.Apply

O where() proporciona melhor segurança e perfomance do que o apply(), no geral.

In [ ]:
vendas_db["VALORUNITARIO"] = np.where(
    vendas_db["VOLUME"] > 0, 
    vendas_db["VALORLIQUIDO"] / vendas_db["VOLUME"],
    0 
)

In [130]:
vendas_db[["VALORLIQUIDO", "VOLUME", "VALORUNITARIO"]].sample(5)

       VALORLIQUIDO  VOLUME  VALORUNITARIO
39326       5728.25     125         45.826
33521        889.58       5        177.916
16359      16733.28       0          0.000
301           65.96       1         65.960
25299        161.45       1        161.450

In [ ]:
vendas_db["CLASSIFICACAO_VALOR"] = np.select(
    [
        vendas_db["VALORLIQUIDO"] >= 5000,
        vendas_db["VALORLIQUIDO"] >= 3500
    ],
    [
        "Alto",
        "Mediano"
    ],
    default="Baixo"
)