In [2]:
import pandas as pd

In [3]:
vendas_db_caminho = 'db\\Base_analitica_vendas.xlsx'

In [4]:
vendas_db = pd.read_excel(vendas_db_caminho, sheet_name='Base')

# Seleção

### **Loc**: trabalha com nomes das colunas.
### **ILoc**: trabalha com índices das colunas.

In [5]:
# vendas_db.loc[200:210, ["CODIGOCLIENTE", "CODIGOPRODUTO", "NOMEPRODUTO"]] 
vendas_db.iloc[200:210, [1, 5, 6]] 
# vendas_db.loc[:, ["CODIGOCLIENTE", "CODIGOPRODUTO", "NOMEPRODUTO"]]

     CODIGOCLIENTE  CODIGOPRODUTO                           NOMEPRODUTO
200       10004001       10021539            Hard Seltzer Guaraná 310ml
201       10004002       10001628   Cerveja Lager Standard 350ml (Lata)
202       10004002       10021324              Néctar de Uva Premium 1L
203       10004002       10026538   Lúpulo em Pellet para Brassagem 5kg
204       10004002       10024278      Vinho Tinto Merlot Chileno 750ml
205       10004002       10003698     Gin Tônica Frutas Vermelhas 269ml
206       10004002       10005779           Margarita Pronta Lata 269ml
207       10004002       10015725    Cachaça Envelhecida Clássica 600ml
208       10004002       10021924  Cerveja Pilsen Regional do Sul 600ml
209       10004002       10020281  Energético Red Blue Sugar Free 250ml

# Filtragem

In [6]:
vendas_db[vendas_db["VALORLIQUIDO"] >= 10_000].drop_duplicates()

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
69,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013094,Bebidas Energéticas Premium,10020281,Energético Red Blue Sugar Free 250ml,1,VENDA,44,10528.45
72,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1400,46949.50
74,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,1,VENDA,77,10059.18
75,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,1,VENDA,198,26568.37
76,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,1,VENDA,151,23611.97
...,...,...,...,...,...,...,...,...,...,...,...
40599,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,1,VENDA,115,18154.55
40600,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,1,VENDA,214,34894.29
40601,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,1,VENDA,273,51799.44
40602,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,1,VENDA,157,37700.30
40603,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015853,Drink Misto Fire 269ml,1,VENDA,39,10571.59

In [14]:
vendas_db[vendas_db["DESCRICAOTIPOFATURAMENTO"].isin(["DEVOLUÇÃO DE VENDA", "DEVOLUÇÃO DE COMPRA"])].sample(10)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
26967,2026-02-20,10004011,DISTRIBUIDORA BEM-ESTAR BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015854,Pack Econômico Drink Misto 269ml,2,DEVOLUÇÃO DE VENDA,-1,-72.12
33649,2026-02-23,10004234,LOGÍSTICA BEBIDAS ATACADO FELIZ,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,2,DEVOLUÇÃO DE VENDA,-4,-835.64
17407,2026-02-13,10004234,LOGÍSTICA BEBIDAS ATACADO FELIZ,90013094,Bebidas Energéticas Premium,10020281,Energético Red Blue Sugar Free 250ml,2,DEVOLUÇÃO DE VENDA,-2,-433.21
22305,2026-02-16,10004201,SUPRIMENTOS PREMIUM BEVERAGES,90013082,Cervejas Regionais,10021924,Cerveja Pilsen Regional do Sul 600ml,2,DEVOLUÇÃO DE VENDA,-25,-1347.25
28060,2026-02-21,10000449,ATACADO BRINDE & CIA,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,2,DEVOLUÇÃO DE VENDA,-1,-163.94
16684,2026-02-13,10004211,DISTRIBUIDORA TUDO EM BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,2,DEVOLUÇÃO DE VENDA,-1,-214.99
5986,2026-02-06,10004006,SUPRIMENTOS GARRAFAS & COPO,90013060,Bebidas Prontas para Consumo (RTD),10005771,Pack 6 Unidades Gin Tônica 269ml,2,DEVOLUÇÃO DE VENDA,-2,-168.42
40378,2026-02-28,10004234,LOGÍSTICA BEBIDAS ATACADO FELIZ,91503404,Bebidas Gasosas Saborizadas,10022636,Água Tônica Tradicional 350ml,2,DEVOLUÇÃO DE VENDA,-2,-185.82
22256,2026-02-16,10004011,DISTRIBUIDORA BEM-ESTAR BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,2,DEVOLUÇÃO DE VENDA,-1,-208.72
5995,2026-02-06,10004006,SUPRIMENTOS GARRAFAS & COPO,90013153,Refrigerantes Sabor Cola,10001864,Refri Cola Original 250ml,2,DEVOLUÇÃO DE VENDA,-2,-116.48

In [26]:
vendas_db[
    (vendas_db["DESCRICAOTIPOFATURAMENTO"] == "DEVOLUÇÃO DE VENDA") |
    (vendas_db["DESCRICAOTIPOFATURAMENTO"] == "DEVOLUÇÃO DE COMPRA") &
    (vendas_db["VOLUME"] <= -50)
    ].sample(8)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
6891,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015853,Drink Misto Fire 269ml,2,DEVOLUÇÃO DE VENDA,-10,-2013.05
1970,2026-02-02,10004203,ATACADISTA BRINDE FINO,91503402,Bebidas Energéticas Funcionais,10022946,Energético Focus Max 250ml (Lata),2,DEVOLUÇÃO DE VENDA,-2,-354.86
6485,2026-02-06,10004215,CENTRAL DE SUPRIMENTOS DE BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,2,DEVOLUÇÃO DE VENDA,-2,-361.88
19096,2026-02-14,10004227,LOGÍSTICA INTEGRAL DE BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015855,Drink Misto Pineapple 269ml,2,DEVOLUÇÃO DE VENDA,-4,-187.91
20153,2026-02-15,10004005,DISTRIBUIDORA SABOR DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,2,DEVOLUÇÃO DE VENDA,-5,-655.90
32345,2026-02-23,10004004,CENTRAL DE NUTRIÇÃO E BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,2,DEVOLUÇÃO DE VENDA,-25,-1124.51
29832,2026-02-21,10004237,LOGÍSTICA MUNDO DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015853,Drink Misto Fire 269ml,2,DEVOLUÇÃO DE VENDA,-3,-866.82
14646,2026-02-11,10004003,REDE BRINDE FELIZ DISTRIBUIÇÃO,90013060,Bebidas Prontas para Consumo (RTD),10003702,Vodka e Maçã Verde Lata 269ml,2,DEVOLUÇÃO DE VENDA,-3,-447.84

In [28]:
vendas_db.query("VOLUME >= 1000 & VOLUME < 2000").head(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
72,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1400,46949.50
4968,2026-02-05,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022283,Isotônico Tangerina Vitaminado 500ml,1,VENDA,1000,233305.80
5938,2026-02-06,10004005,DISTRIBUIDORA SABOR DAS BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1300,53963.50
6985,2026-02-06,10004231,DISTRIBUIDORA REINO DAS BEBIDAS,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml,1,VENDA,1325,44021.35
7792,2026-02-07,10004005,DISTRIBUIDORA SABOR DAS BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1200,48909.00

In [ ]:
tipo_faturamento = 1
volume = 1000

vendas_db.query(f"TIPOFATURAMENTO == {tipo_faturamento} | VOLUME >= @volume").head(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07

O uso dos dois tipos de interpolação é contraindicado, use o de sua preferência. Entretanto o mais recomendado para segurança é com @

In [31]:
vendas_db["DESCRICAOTIPOFATURAMENTO"].unique()

<StringArray>
['VENDA', 'BONIFICAÇÃO', 'DEVOLUÇÃO DE VENDA', 'DEVOLUÇÃO DE COMPRA',
 'COMPRA']
Length: 5, dtype: str

In [32]:
vendas_db["DESCRICAOTIPOFATURAMENTO"].value_counts()

DESCRICAOTIPOFATURAMENTO
VENDA                  36476
BONIFICAÇÃO             2552
COMPRA                   911
DEVOLUÇÃO DE VENDA       671
DEVOLUÇÃO DE COMPRA       11
Name: count, dtype: int64

In [39]:
vendas_db.sort_values(["VOLUME", "VALORLIQUIDO"], ascending=[False, True]).head(3)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
19245,2026-02-14,10004231,DISTRIBUIDORA REINO DAS BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1600,63063.60
27784,2026-02-20,10004234,LOGÍSTICA BEBIDAS ATACADO FELIZ,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1550,58071.25
18801,2026-02-14,10004219,SUPRIMENTOS MASTER BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,1550,58706.93