In [16]:
import pandas as pd 
import numpy as np
import os
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
vendas_db_caminho = 'db\\Base_analitica_vendas_periodo.xlsx'

In [3]:
vendas_db_dezembro = pd.read_excel(vendas_db_caminho, sheet_name='Dez')
vendas_db_janeiro = pd.read_excel(vendas_db_caminho, sheet_name='Jan')
vendas_db_fevereiro = pd.read_excel(vendas_db_caminho, sheet_name='Fev')

In [4]:
vendas_db_dezembro = vendas_db_dezembro.rename(columns={
    "DATA": "DATAEMISSAO"
})

In [5]:
vendas_db = pd.concat(
    [
        vendas_db_dezembro,
        vendas_db_janeiro,
        vendas_db_fevereiro    
    ],
    ignore_index=True
)

In [7]:
vendas_db["MÊS"] = vendas_db.DATAEMISSAO.dt.month_name(locale="pt_BR")

In [8]:
vendas_db

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,MÊS
0,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,1,VENDA,1315,7311.40,Dezembro
1,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,730,4015.00,Dezembro
2,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015857,Drink Misto Peach 269ml,1,VENDA,2000,28440.00,Dezembro
3,2025-12-01,10001683,ATACADISTA BRINDE AMIGO,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,26,377.26,Dezembro
4,2025-12-01,10004002,COMERCIAL MUNDO DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,3,BONIFICAÇÃO,15,55.05,Dezembro
...,...,...,...,...,...,...,...,...,...,...,...,...
106659,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52,Fevereiro
106660,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32,Fevereiro
106661,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94,Fevereiro
106662,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10,Fevereiro
106663,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88,Fevereiro

### Exportação

In [12]:
os.makedirs("exportacoes", exist_ok=True)

In [ ]:
vendas_db.to_excel("exportacoes\\Base vendas Dez, Jan, Fev.xlsx", index=False)

In [13]:
vendas_db.to_csv("exportacoes\\Base vendas Dez, Jan, Fev.csv", sep=";", index=False, encoding="utf-8")

In [14]:
vendas_db.to_json("exportacoes\\Base vendas Dez, Jan, Fev.json", orient="records", force_ascii=False, date_format="iso", indent=4)

In [23]:
vendas_db.pivot_table(
    values=["VALORLIQUIDO"],
    index=["MÊS"],
    columns=["DESCRICAOGRUPOPRODUTO"],
    aggfunc="sum"
)

                                      VALORLIQUIDO  \
DESCRICAOGRUPOPRODUTO Base para Bebidas Alcoólicas
MÊS
Dezembro                                 39,473.53
Fevereiro                                 1,963.05
Janeiro                                 125,592.09

                                                      \
DESCRICAOGRUPOPRODUTO Bebidas Energéticas Funcionais
MÊS
Dezembro                               25,910,203.13
Fevereiro                               4,040,350.56
Janeiro                                30,730,991.68

                                                                               \
DESCRICAOGRUPOPRODUTO Bebidas Energéticas Premium Bebidas Funcionais Naturais
MÊS
Dezembro                            22,141,232.01                   93,083.08
Fevereiro                            4,853,774.76                    2,850.95
Janeiro                             25,901,541.52                   70,964.32

                                                      \
DESCRICAOGRUPOPRODUTO Bebidas Funcionais Vitaminadas
MÊS
Dezembro                               15,397,990.26
Fevereiro                               4,805,289.85
Janeiro                                17,792,760.73

                                                                        \
DESCRICAOGRUPOPRODUTO Bebidas Gasosas Saborizadas Bebidas Ice e Cooler
MÊS
Dezembro                            22,500,259.54         2,909,284.12
Fevereiro                            2,241,998.95         2,124,308.88
Janeiro                             27,390,970.06         2,878,772.79

                                                                      \
DESCRICAOGRUPOPRODUTO Bebidas Mistas Alcoólicas Bebidas Nutricionais
MÊS
Dezembro                          82,400,597.39           109,241.51
Fevereiro                         60,145,298.54               673.77
Janeiro                           96,157,237.74            95,555.22

                                               ...                             \
DESCRICAOGRUPOPRODUTO Bebidas Prontas Geladas  ... Matéria-prima para Bebidas
MÊS                                            ...
Dezembro                        17,029,031.04  ...                 114,566.25
Fevereiro                        1,842,549.62  ...                  14,071.45
Janeiro                         20,288,164.96  ...                  69,390.13

                                                     \
DESCRICAOGRUPOPRODUTO Produção de Bebidas em Escala
MÊS
Dezembro                                 141,088.23
Fevereiro                                  1,854.53
Janeiro                                  137,806.11

                                                            \
DESCRICAOGRUPOPRODUTO Produção de Bebidas em Grande Escala
MÊS
Dezembro                                      2,298,354.74
Fevereiro                                       582,369.34
Janeiro                                       2,600,119.36

                                                                      \
DESCRICAOGRUPOPRODUTO Refrigerantes Premium Refrigerantes Sabor Cola
MÊS
Dezembro                          11,395.44            11,295,098.71
Fevereiro                            162.20               568,012.38
Janeiro                           48,701.19            13,387,408.72

                                                                             \
DESCRICAOGRUPOPRODUTO Refrigerantes Sabor Frutas Refrigerantes Tradicionais
MÊS
Dezembro                            3,522,442.84               1,379,910.65
Fevereiro                             259,390.21                  78,709.76
Janeiro                             4,242,495.46               1,115,623.30

                                                                       \
DESCRICAOGRUPOPRODUTO Sucos Naturais Premium Vinhos Tintos Importados
MÊS
Dezembro                       20,198,977.41            11,316,748.22
Fevereiro                       3,366,567.61             3,331,726.47
Janeiro                        23,637,785.49            14,075,851.30


DESCRICAOGRUPOPRODUTO Vinhos e Espumantes
MÊS
Dezembro                       127,569.15
Fevereiro                        6,844.11
Janeiro                        114,061.06

[3 rows x 48 columns]

In [24]:
vendas_db.groupby(["MÊS", "DESCRICAOGRUPOPRODUTO"])["VALORLIQUIDO"].sum().reset_index()

          MÊS           DESCRICAOGRUPOPRODUTO  VALORLIQUIDO
0    Dezembro    Base para Bebidas Alcoólicas     39,473.53
1    Dezembro  Bebidas Energéticas Funcionais 25,910,203.13
2    Dezembro     Bebidas Energéticas Premium 22,141,232.01
3    Dezembro     Bebidas Funcionais Naturais     93,083.08
4    Dezembro  Bebidas Funcionais Vitaminadas 15,397,990.26
..        ...                             ...           ...
138   Janeiro      Refrigerantes Sabor Frutas  4,242,495.46
139   Janeiro      Refrigerantes Tradicionais  1,115,623.30
140   Janeiro          Sucos Naturais Premium 23,637,785.49
141   Janeiro        Vinhos Tintos Importados 14,075,851.30
142   Janeiro             Vinhos e Espumantes    114,061.06

[143 rows x 3 columns]