In [ ]:
import pandas as pd

In [7]:
vendas_db_caminho = 'db\\Base_analitica_vendas.xlsx'

In [8]:
vendas_db = pd.read_excel(vendas_db_caminho, sheet_name='Base')

Exibindo dados como de planilhas (topo, inferior e aleatório, respectivamente)

In [17]:
# vendas_db.head(5)
# vendas_db.tail(5)
vendas_db.sample(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
36095,2026-02-25,10004236,ATACADISTA SELEÇÃO DE BEBIDAS,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1396.55
22001,2026-02-16,10004004,CENTRAL DE NUTRIÇÃO E BEBIDAS,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,6,606.62
3035,2026-02-03,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013094,Bebidas Energéticas Premium,10020283,Energético Red Blue Summer Edition 250ml,3,BONIFICAÇÃO,2,693.10
39749,2026-02-28,10004219,SUPRIMENTOS MASTER BEBIDAS,90013094,Bebidas Energéticas Premium,10020281,Energético Red Blue Sugar Free 250ml,1,VENDA,12,2518.38
21887,2026-02-16,10004002,COMERCIAL MUNDO DAS BEBIDAS,90013032,Vinhos Tintos Importados,10024278,Vinho Tinto Merlot Chileno 750ml,1,VENDA,60,1676.42

### Tipos (DataFrame, Series)

#### Series 
Coluna de uma Dataframe, se comporta semelhantemente a uma array. Além disso, quando chamado exibe as primeiras e últimas 5 linhas da coluna. 

#### DataFrame
Uma planilha inteira num tipo Python.

In [20]:
series = vendas_db["CODIGOCLIENTE"]
series

0        10000449
1        10000449
2        10000449
3        10000449
4        10000449
           ...
40616    10005002
40617    10005002
40618    10005002
40619    10005002
40620    10005002
Name: CODIGOCLIENTE, Length: 40621, dtype: int64

In [19]:
dataframe = vendas_db[["CODIGOCLIENTE"]]
dataframe

       CODIGOCLIENTE
0           10000449
1           10000449
2           10000449
3           10000449
4           10000449
...              ...
40616       10005002
40617       10005002
40618       10005002
40619       10005002
40620       10005002

[40621 rows x 1 columns]

### Funções/Atributos úteis

#### Columns
Autoexplicativo.

#### Dtypes
Tipagem de cada coluna.

#### Info
Como o anterior, mas mais alguns detalhes.

#### Describe
Exibe alguns dados úteis como média, min, max etc.

In [22]:
# vendas_db.columns
# vendas_db.dtypes
# vendas_db.info()
vendas_db.describe()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOGRUPOPRODUTO,CODIGOPRODUTO,TIPOFATURAMENTO,VOLUME,VALORLIQUIDO
count,40621,4.062100e+04,4.062100e+04,4.062100e+04,40621.000000,40621.000000,4.062100e+04
mean,2026-02-14 19:14:50.583688,1.000386e+07,9.030686e+07,1.039773e+07,1.414810,31.207700,3.136858e+03
min,2026-02-01 00:00:00,1.000045e+07,9.001300e+07,1.000116e+07,1.000000,-300.000000,-1.851525e+04
25%,2026-02-08 00:00:00,1.000400e+07,9.001306e+07,1.000778e+07,1.000000,2.000000,3.202900e+02
50%,2026-02-15 00:00:00,1.000421e+07,9.001316e+07,1.001585e+07,1.000000,6.000000,9.080400e+02
75%,2026-02-22 00:00:00,1.000423e+07,9.001317e+07,1.002228e+07,1.000000,25.000000,2.448270e+03
max,2026-02-28 00:00:00,1.000500e+07,9.150341e+07,9.001344e+07,14.000000,1600.000000,1.122164e+06
std,NaN,9.718213e+02,5.928791e+05,4.476117e+06,1.836045,85.129167,1.154109e+04